#==================== gateway ====================
spring: 
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 2000MB # 设置单个文件的最大长度
      max-request-size: 2000MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: c:/  # 上传的临时目录
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  cloud:
    bus:
      trace:
        enabled: true
management:
  security:
    enabled: false

logging:
  config: classpath:logback-local.xml
  path: c://logs//
zuul:
  info:
    request: true
  host:
    connect-timeout-millis: 6000000
    socket-timeout-millis: 6000000
  routes:
    user:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials
      path: /user/**
      serviceId: vm-provider-user
      stripPrefix: false
    src:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials
      path: /src/**
      serviceId: vm-provider-src
      stripPrefix: false
    filmmaker:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials
      path: /filmmaker/**
      serviceId: vm-provider-movie
      stripPrefix: false
    movie:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials
      path: /movie/**
      serviceId: vm-provider-movie
      stripPrefix: false
    tagGroup:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials
      path: /tagGroup/**
      serviceId: vm-provider-movie
      stripPrefix: false
    tag:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials
      path: /tag/**
      serviceId: vm-provider-movie
      stripPrefix: false
    admin:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials
      path: /admin/**
      serviceId: vm-provider-admin
      stripPrefix: false
    adminWS:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials
      path: /adminWS/**
      serviceId: vm-provider-admin-ws
    ws:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials
      path: /ws/**
      serviceId: vm-provider-ws
feign:
  hystrix:
    enabled: true

vm-provider-ws: 
  ribbon:
    NFLoadBalancerRuleClassName: com.vm.gateway.rules.IpHashRule
ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
  ServerListRefreshInterval: 5000 #eureka客户端ribbon刷新时间,默认30s



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000

  
