#==================== gateway ====================
spring: 
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 2000MB # 设置单个文件的最大长度
      max-request-size: 2000MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: d:/  # 上传的临时目录
  rabbitmq:
    host: 39.108.231.231
    port: 5672
    username: root
    password: 123
  cloud:
    bus:
      trace:
        enabled: true
management:
  security:
    enabled: false

logging:
  config: classpath:logback-local.xml
  path: d://logs//
zuul:
  info:
    request: true
  host:
    connect-timeout-millis: 6000000
    socket-timeout-millis: 6000000
  routes:
    user:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /user/**
      serviceId: vm-provider-user
      stripPrefix: false
    src:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /src/**
      serviceId: vm-provider-src
      stripPrefix: false
    filmmaker:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /filmmaker/**
      serviceId: vm-provider-movie
      stripPrefix: false
    movie:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /movie/**
      serviceId: vm-provider-movie
      stripPrefix: false
    tagGroup:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /tagGroup/**
      serviceId: vm-provider-movie
      stripPrefix: false
    tag:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /tag/**
      serviceId: vm-provider-movie
      stripPrefix: false
    admin:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /admin/**
      serviceId: vm-provider-admin
      stripPrefix: false
    adminWS:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /adminWS/**
      serviceId: vm-provider-admin
feign:
  hystrix:
    enabled: false


ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
  ServerListRefreshInterval: 5000 #eureka客户端ribbon刷新时间,默认30s



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000

  