#==================== gateway ====================
spring: 
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 2000MB # 设置单个文件的最大长度
      max-request-size: 2000MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: d:/  # 上传的临时目录
logging:
  config: classpath:logback-dev.xml
  path: d://logs//
zuul:
  info:
    request: true
  ratelimit:
    enabled: true #default false
    behind-proxy: true #default false
    repository: Redis
    default-policy-list: #optional - will apply unless specific policy exists
      limit: 100 #optional - request number limit per refresh interval window
      refresh-interval: 120 #default value (in seconds)
      type: origin
    policies:
      vm-provider-user:
        limit: 10
        refresh-interval: 120 #60 default value (in seconds)
        type: origin
      vm-provider-movie:
        limit: 100
        refresh-interval: 120 #60 default value (in seconds)
        type: origin
      vm-provider-admin:
        limit: 100
        refresh-interval: 120 #60 default value (in seconds)
        type: origin
      vm-provider-src:
        limit: 100
        refresh-interval: 120 #60 default value (in seconds)
        type: origin
  host:
    connect-timeout-millis: 6000000
    socket-timeout-millis: 6000000
  routes:
    user:
      path: /user/**
      serviceId: vm-provider-user
      stripPrefix: false
    src:
      path: /src/**
      serviceId: vm-provider-src
      stripPrefix: false
    filmmaker:
      path: /filmmaker/**
      serviceId: vm-provider-movie
      stripPrefix: false
    movie:
      path: /movie/**
      serviceId: vm-provider-movie
      stripPrefix: false
    tagGroup:
      path: /tagGroup/**
      serviceId: vm-provider-movie
      stripPrefix: false
    tag:
      path: /tag/**
      serviceId: vm-provider-movie
      stripPrefix: false
    admin:
      path: /admin/**
      serviceId: vm-provider-admin
      stripPrefix: false
feign:
  hystrix:
    enabled: false


ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
  ServerListRefreshInterval: 5000 #eureka客户端ribbon刷新时间,默认30s



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000

  