#==================== gateway ====================
spring: 
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /usr/local/src/  # 上传的临时目录
logging:
  config: classpath:logback.xml
  path: /usr/local/src/logs/
zuul:
  info:
    request: true
  host:
    connect-timeout-millis: 6000000
    socket-timeout-millis: 6000000
  routes:
    user:
      path: /user/**
      serviceId: vm-provider-user
      stripPrefix: false
    src:
      path: /src/**
      serviceId: vm-provider-src
      stripPrefix: false
    filmmaker:
      path: /filmmaker/**
      serviceId: vm-provider-movie
      stripPrefix: false
    movie:
      path: /movie/**
      serviceId: vm-provider-movie
      stripPrefix: false
    tagGroup:
      path: /tagGroup/**
      serviceId: vm-provider-movie
      stripPrefix: false
    tag:
      path: /tag/**
      serviceId: vm-provider-movie
      stripPrefix: false
    admin:
      path: /admin/**
      serviceId: vm-provider-admin
      stripPrefix: false
feign:
  hystrix:
    enabled: true


ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
  ServerListRefreshInterval: 5000 #eureka客户端ribbon刷新时间,默认30s



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000

