#==================== gateway ====================
logging:
  config: classpath:logback.xml
  path: d://logs//

feign:
  hystrix:
    enabled: false


ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
  ServerListRefreshInterval: 5000 #eureka客户端ribbon刷新时间,默认30s



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000

  