# spring
spring:
  #db connection
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.191.94:3306/vm_src?useUnicode=true&amp;characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull&amp;allowMultiQueries=true&amp;autoReconnect=true
    username: root
    password: 123
    # for initial,min,max
    initialSize: 5
    minIdle: 5
    maxActive: 100
    # sql for validating
    validationQuery: SELECT 1
    # this will validate idle connection.if validation failed, will remove from pool
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # max wait time
    maxWait: 6000000
    timeBetweenEvictionRunsMillis: 30000

logging:
  level:
    com.vm.src.dao.mapper: debug



vm:
  src:
    img:
      url: /src/img
      default: default.png
      maxSize: 2097152
      allowSuffix: jpg,png
      path: /usr/local/vm/src/img/
    video:
      url: /src/video
      default: default.mp4
      path: /usr/local/vm/src/video/

