# spring
spring:
  #db connection
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.191.94:3306/vm_movie?useUnicode=true&amp;characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull&amp;allowMultiQueries=true&amp;autoReconnect=true
    username: root
    password: 123
    # for initial,min,max
    initialSize: 5
    minIdle: 5
    maxActive: 100
    # sql for validating
    validationQuery: SELECT 1
    # this will validate idle connection.if validation failed, will remove from pool
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # max wait time
    maxWait: 6000000
    timeBetweenEvictionRunsMillis: 30000

logging:
  level:
    com.vm.movie.dao.mapper: debug
    com.vm.movie.feign.service: debug

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000
feign:
  hystrix:
    enabled: false
vm:
  movie:
    img:
      versions: 50,80,300
    poster:
      versions: 50,80,200,600,1000